# Generated by Django 3.2 on 2021-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
